bookscensor/accounts/urls.py
from django.urls import path, include
from .views import registration, RegistrationClass, LoginClass, LogoutClass

app_name="accounts"

urlpatterns = [
    path('registrsation/', RegistrationClass.as_view(), name="registration"),
    path('login/', LoginClass.as_view(), name="login"),
    path('logout/', LogoutClass.as_view(), name="logout"),


]

bookscensor/bookscensor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookssite.urls')),
    path('accounts/', include("accounts.urls"))
]

bookscensor/bookssite/urls.py
from django.urls import path, include
from .views import BookListView, BookDetailView, ReviewUpdate, ReviewDelete, BookAdd

urlpatterns = [
    path('', BookListView.as_view(), name="index"),
    path('book/<int:pk>/', BookDetailView.as_view(), name="book_detail"),
    path('review_update/<int:pk>/', ReviewUpdate.as_view(), name="review_update"),
    path('review_delete/<int:pk>/', ReviewDelete.as_view(), name="review_delete"),
    path('book_add/', BookAdd.as_view(), name="book_add"),

]

bookscensor/accounts/models.py
from django.db import models

# Create your models here.

bookscensor/bookssite/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    author = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.title} by {self.author}"


class Review(models.Model):
    RATING = [
        ('5', 5),
        ('4', 4),
        ('3', 3),
        ('2', 2),
        ('1', 1),
    ]
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.TextField()
    review_create = models.DateTimeField(auto_now_add=True)
    review_update = models.DateTimeField(auto_now=True)
    rating = models.CharField(max_length=1, choices=RATING, default='5')

    def __str__(self):
        return f"Review about {self.book} by user: {self.user}"

bookscensor/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class NewUserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']

bookscensor/bookssite/forms.py
from django import forms

from .models import Review, Book


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('review', 'rating')

bookscensor/accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import AuthenticationForm
from .forms import NewUserRegistrationForm
# Create your views here.

class LoginClass(FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('index')
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        user = authenticate(username=self.request.POST['username'], password=self.request.POST['password'])
        login(self.request, user)
        return super(LoginClass, self).form_valid(form)

class LogoutClass(LoginRequiredMixin, LogoutView):

    redirect_field_name = 'index'
    template_name = "accounts/logout.html"


class RegistrationClass(FormView):
    form_class = NewUserRegistrationForm
    success_url = reverse_lazy('index')
    template_name = 'accounts/registration.html'

    def form_valid(self, form):
        form.save()
        return super(RegistrationClass, self).form_valid(form)

def registration(request):
    if request.method == "POST":
        form=NewUserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form=NewUserRegistrationForm()
    return render(request, 'accounts/registration.html', {'form': form})

bookscensor/bookssite/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic.list import ListView, View
from django.views.generic.edit import FormMixin, UpdateView, DeleteView, CreateView
from django.views.generic.detail import DetailView, SingleObjectMixin
from .models import Book, Review
from .forms import ReviewForm
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
# Create your views here.

class BookListView(ListView):
    model = Book
    template_name = "bookssite/index.html"


class BookDetailView(FormMixin, DetailView):
    model = Book
    template_name = "bookssite/book_detail.html"
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['review_list'] = Review.objects.filter(book=self.get_object())

        return context

    def get_success_url(self):
        return reverse('book_detail', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            obj = form.save(commit=False)
            obj.book = self.object
            obj.user = request.user
            obj.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # Here, we would record the user's interest using the message
        # passed in form.cleaned_data['message']

        return super().form_valid(form)


class ReviewUpdate(UserPassesTestMixin, UpdateView):
    model = Review
    fields = ['review', 'rating']
    template_name = "bookssite/review_update.html"

    def test_func(self):
        review = self.get_object()
        if self.request.user == review.user:
            return True
        return False

    def get_success_url(self):
        return reverse('book_detail', kwargs={'pk': self.object.book.id})


class ReviewDelete(UserPassesTestMixin, DeleteView):
    model = Review
    success_url = reverse_lazy('index')

    def test_func(self):
        review = self.get_object()
        if self.request.user == review.user:
            return True
        return False


class BookAdd(CreateView):
    model = Book
    fields = '__all__'
    template_name = "bookssite/add_book.html"
    success_url = '/'

bookscensor/accounts/templates/accounts/login.html
{% extends 'bookssite/base.html' %}
{% block content %}
<form method="post">
     {% csrf_token %}
    {{ form }}
    <input type="submit" value="Log In">
</form>
{% endblock content %}

bookscensor/accounts/templates/accounts/logout.html
{% extends 'bookssite/base.html' %}
{% block content %}
you successfully logged out!
{% endblock content %}

bookscensor/accounts/templates/accounts/registration.html
{% extends 'bookssite/base.html' %}
{% block content %}

<form action="" method="POST" style="border:2px solid black; width:50%;">
   {% csrf_token %}

  {{ form.as_p }}
<input type="submit" value="Submit">

</form>
{% endblock content %}

bookscensor/bookssite/templates/bookssite/add_book.html
{% extends 'bookssite/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock content %}

bookscensor/bookssite/templates/bookssite/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
      <link type="text/css" href="{% static 'style.css' %}" rel="stylesheet" />
    <meta charset="UTF-8">
    <title>BookStore</title>
</head>
<body>
<ul>
  <li><a href="{% url 'index' %}">Home</a></li>
  <li><a href="{% url 'book_add' %}">Add book</a></li>

</ul>
{% block content %} {% endblock%}
</body>
</html>

bookscensor/bookssite/templates/bookssite/book_detail.html
{% extends 'bookssite/base.html' %}
{% block content %}


<h1>{{ object.title }}</h1>
<p>{{ object.description }}</p>
<p> {{ object.author }}</p>

{% if user.is_authenticated %}
<h2>Leave a review</h2>
<div>
    <form method="post">{% csrf_token %}
{{ form.as_p }}
    <input type="submit" value="Make the review">
</form>
</div>
{% else %}
<p style="color:red;">If you want to write a review, please <a href="{% url 'accounts:login' %}">Log in</a> or make a registration <a href="{% url 'accounts:registration' %}">Registration</a></p>
{% endif %}


<h2>Reviews</h2>
{% for review in review_list %}

<div class="box">
    <div class="profile">
       <div class="rating">
           {{ review.rating }}
    </div>
        <div class="bio">
            <h2>{{ review.user }}</h2> <h4>published: {{ review.review_create}}  </h4>
        </div>
    </div>
    {% if request.user ==  review.user %}
    <a href="{% url 'review_update' review.id %}"> update </a> | <a href="{% url 'review_delete' review.id %}">delete</a>
    {% endif %}
    <div class="review">
        {{ review.review }}
    </div>
</div>
{% endfor %}

{% endblock content %}

bookscensor/bookssite/templates/bookssite/index.html
{% extends 'bookssite/base.html' %}
{% block content %}
<div style="">
<a href="{% url 'accounts:registration' %}">Registration</a> |
<a href="{% url 'accounts:login' %}">Log in</a>
</div>
<br>
<div>
{% if user.is_authenticated %}
Hello, <b>{{ user }}!</b> You are in the site!
 <a href="{% url 'accounts:logout' %}">Log out!</a>
{% else %}
You aren't in the site!
{% endif %}
</div>

{% for book in object_list %}
<p>
 {{ book }}
 <a href="{% url 'book_detail' book.id %}">Detail...</a>
</p>
{% endfor %}

{% endblock content %}

bookscensor/bookssite/templates/bookssite/review_confirm_delete.html
{% extends 'bookssite/base.html' %}
{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the review? "{{ object }}"?</p>

    <input type="submit" value="Yes">
    <a type="button" href="{% url 'book_detail' object.book.id %}">No</a>
</form>
{% endblock content %}

bookscensor/bookssite/templates/bookssite/review_update.html
{% extends 'bookssite/base.html' %}
{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock content %}